services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - redis_network
    environment:
      - REDIS_PASSWORD="password"
    command: ["redis-server"]
    volumes:
      - redis_data:/data

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
